#!/usr/bin/env bash
# installs nginx
# print "Hello World"

sudo apt -y update
sudo apt -y install nginx
cat << EOF | sudo tee /var/www/html/index.nginx-debian.html >> /dev/null
Hello World!
EOF

sudo service nginx start
