#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sed -i '/server_name _/c\
\tserver_name _;\
\n\tlocation /redirect_me {\
\t\t#Redirects to youtube page\
\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\t}\
' /etc/nginx/sites-enabled/default

service nginx restart
