#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

sed -i '/server_name _/c\
\tserver_name _;\
\n\tlocation /redirect_me {\
\t\t#Redirects to youtube page\
\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\t}\
' /etc/nginx/sites-available/default

service nginx restart
