#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

sed -i '/listen 80*/a  \\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

sed -i '/index index.html*/a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-enabled/default

service nginx restart
