#!/usr/bin/env bash
# Install and Configure HAProxy

file="/etc/haproxy/haproxy.cfg"

apt-get -y update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk

echo "ENABLED=1" | tee -a /etc/default/haproxy > /dev/null

tee -a $file << EOF > /dev/null

frontend haproxy-main
	bind *:80
	mode http
	option http-keep-alive
	default_backend nginx_webservers

backend nginx_webservers
	mode http
	balance roundrobin
	server 8248-web-02 54.175.133.2:80 check
	server 8248-web-01 52.86.109.82:80 check
EOF

service haproxy start
