#!/usr/bin/env bash
# Install and Configure HAProxy

file="/etc/haproxy/haproxy.cfg"

sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk

sudo tee -a $file << EOF > /dev/null

frontend haproxy-main
	bind *:80
	option forwardfor
	stats uri /haproxy?stats
	default_backend nginx_webservers

backend nginx_webservers
	balance roundrobin
	server 8248-web-02 54.175.133.2:80 check
	server 8248-web-01 52.86.109.82:80 check
EOF
