#!/usr/bin/env bash
# Configures nginx to port 80
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/server_name localhost/server_name _/g' /etc/nginx/sites-enabled/default
apt-get -y install lsof && kill "$(lsof -i:8080 -t)"
service nginx restart
