#!/usr/bin/env bash
# Print output using while loop
n=1
while [ $n != 11 ];
do
	if [ $n == 4 ];
	then
		echo "bad luck"
	elif [ $n == 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n=n+1))
done
