#!/usr/bin/env bash
# Check file status

if [ -a school ];
then
	echo "school file exists"
	if [ ! -s school ];
	then
		echo "school file is empty"
	fi

	if [ -s school ];
	then
		echo "school file is not empty"
	fi

	if [ -f school ];
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
